// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/4/29 18:08:09
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/tevin/Desktop/mm_project/mini_app_share/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tevin/Desktop/mm_project/mini_app_share/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tevin/Desktop/mm_project/mini_app_share/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tevin/Desktop/mm_project/mini_app_share/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tevin/Desktop/mm_project/mini_app_share/plugins/**/*.{js,ts,mjs}","/Users/tevin/Desktop/mm_project/mini_app_share/composables/**/*.{js,ts,mjs}","/Users/tevin/Desktop/mm_project/mini_app_share/utils/**/*.{js,ts,mjs}","/Users/tevin/Desktop/mm_project/mini_app_share/pages/error.vue","/Users/tevin/Desktop/mm_project/mini_app_share/pages/index/[id].vue","/Users/tevin/Desktop/mm_project/mini_app_share/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tevin/Desktop/mm_project/mini_app_share/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tevin/Desktop/mm_project/mini_app_share/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;